# Generated by Django 5.0.4 on 2024-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=500)),
                ('DisplayOrder', models.IntegerField()),
                ('Code', models.CharField(max_length=250)),
                ('ImgUrl', models.CharField(max_length=250)),
                ('Width', models.IntegerField(null=True)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_categorys',
            },
        ),
    ]
