# Generated by Django 5.0.4 on 2024-04-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='DisplayOrder',
            new_name='displayOrder',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ImgUrl',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Width',
            new_name='width',
        ),
    ]
