# Generated by Django 5.0.4 on 2024-04-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='isAddToCartList',
            new_name='is_add_to_cart_list',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='productId',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='userId',
            new_name='user_id',
        ),
    ]
