# Generated by Django 5.0.4 on 2024-04-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_isaddtocartlist_cart_is_add_to_cart_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
