# Generated by Django 5.0.6 on 2024-05-10 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_created_date_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 10, 16, 59, 46, 19436)),
        ),
    ]
